#!/usr/bin/env bash
# setup.sh — One-shot bootstrap for the Pocket VPN Gateway
# Board: Raspberry Pi Zero 2 W running Raspbian Lite (64-bit)
# Run once as root after first boot: sudo bash setup.sh
set -euo pipefail

WG_SERVER_IP="10.8.0.1/24"
WG_PORT=51820
WG_IFACE="wg0"
DASHBOARD_PORT=8080

echo "==> Updating package lists…"
apt-get update -qq

echo "==> Installing WireGuard and tools…"
apt-get install -y wireguard wireguard-tools iptables-persistent python3-pip 2>/dev/null

echo "==> Installing Python packages…"
pip3 install flask psutil --quiet

echo "==> Generating WireGuard keypair…"
SERVER_PRIV=$(wg genkey)
SERVER_PUB=$(echo "$SERVER_PRIV" | wg pubkey)
echo "Server public key: $SERVER_PUB"
echo "$SERVER_PRIV" > /etc/wireguard/server_private.key
chmod 600 /etc/wireguard/server_private.key

echo "==> Writing /etc/wireguard/wg0.conf…"
cat > /etc/wireguard/wg0.conf <<EOF
[Interface]
Address = ${WG_SERVER_IP}
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIV}

# IP forwarding + masquerade (internet routing via wlan0)
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; \\
           iptables -A FORWARD -o %i -j ACCEPT; \\
           iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; \\
           iptables -D FORWARD -o %i -j ACCEPT; \\
           iptables -t nat -D POSTROUTING -o wlan0 -j MASQUERADE

# Add peer blocks below — each generated by:
#   CLIENT_PRIV=\$(wg genkey)
#   CLIENT_PUB=\$(echo "\$CLIENT_PRIV" | wg pubkey)
# Then on the client: AllowedIPs = 0.0.0.0/0, Endpoint = <pi-public-ip>:${WG_PORT}

# [Peer]
# PublicKey = <client_public_key>
# AllowedIPs = 10.8.0.2/32
EOF
chmod 600 /etc/wireguard/wg0.conf

echo "==> Enabling IPv4 forwarding…"
sed -i 's/^#\?net.ipv4.ip_forward=.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sysctl -p /etc/sysctl.conf

echo "==> Enabling and starting WireGuard…"
systemctl enable wg-quick@${WG_IFACE}
systemctl start  wg-quick@${WG_IFACE}

echo "==> Copying dashboard to /opt/vpn-dashboard/…"
mkdir -p /opt/vpn-dashboard
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cp "$SCRIPT_DIR/main.py" /opt/vpn-dashboard/main.py

echo "==> Creating systemd service for Flask dashboard…"
cat > /etc/systemd/system/vpn-dashboard.service <<EOF
[Unit]
Description=Pocket VPN Gateway Dashboard (Flask)
After=network.target wg-quick@${WG_IFACE}.service

[Service]
ExecStart=/usr/bin/python3 /opt/vpn-dashboard/main.py
WorkingDirectory=/opt/vpn-dashboard
Restart=always
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable vpn-dashboard
systemctl start  vpn-dashboard

echo ""
echo "============================================================"
echo "  Setup complete!"
echo "  WireGuard: wg0 listening on UDP ${WG_PORT}"
echo "  Server public key: ${SERVER_PUB}"
echo "  Dashboard: http://\$(hostname -I | awk '{print \$1}'):${DASHBOARD_PORT}"
echo ""
echo "  To add a client peer:"
echo "    CLIENT_PRIV=\$(wg genkey)"
echo "    CLIENT_PUB=\$(echo \"\$CLIENT_PRIV\" | wg pubkey)"
echo "    sudo wg set wg0 peer \$CLIENT_PUB allowed-ips 10.8.0.X/32"
echo "    sudo wg-quick save wg0"
echo "============================================================"
